//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject_InsuranceManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.AutomobileInsurances = new HashSet<AutomobileInsurance>();
            this.HealthInsurances = new HashSet<HealthInsurance>();
            this.HomeInsurances = new HashSet<HomeInsurance>();
            this.LifeInsurances = new HashSet<LifeInsurance>();
            this.PensionPlans = new HashSet<PensionPlan>();
            this.Purchaseds = new HashSet<Purchased>();
            this.TravelInsurances = new HashSet<TravelInsurance>();
        }
    
        public int CustomerId { get; set; }

        [Required(ErrorMessage = "FirstName field is required")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "FirstName is not valid")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "LastName field is required")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "LastName is not valid")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "MobileNumber field is required")]
        [Range(999999999, 9999999999, ErrorMessage = "Mobile number is not valid")]
        public long MobileNumber { get; set; }
        public Nullable<int> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutomobileInsurance> AutomobileInsurances { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthInsurance> HealthInsurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeInsurance> HomeInsurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LifeInsurance> LifeInsurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PensionPlan> PensionPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchased> Purchaseds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelInsurance> TravelInsurances { get; set; }
    }
}
