//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject_InsuranceManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HomeInsurance
    {
        public Nullable<int> CustomerId { get; set; }
        public string BuildingType { get; set; }

        public Nullable<int> FloorArea { get; set; }

        [Required(ErrorMessage = "City field is required")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "City is not valid")]
        public string City { get; set; }

        [Required(ErrorMessage = "HouseNumber field is required")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "At least 5 characters")]
        public string HouseNumber { get; set; }

 
        public long Valuation { get; set; }

        public int PlanDuration { get; set; }
        public int id { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
