//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject_InsuranceManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insurance()
        {
            this.Purchaseds = new HashSet<Purchased>();
        }
    
        public int InsuranceId { get; set; }
        public string InsuranceType { get; set; }
        public string SubType { get; set; }
        public string FilterParameter { get; set; }
        public Nullable<long> Amount { get; set; }
        public long YearlyPremium { get; set; }
        public string InsuranceProvider { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchased> Purchaseds { get; set; }
    }
}
