//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject_InsuranceManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InsuranceManagementSystemDbEntities1 : DbContext
    {
        public InsuranceManagementSystemDbEntities1()
            : base("name=InsuranceManagementSystemDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutomobileInsurance> AutomobileInsurances { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<HealthInsurance> HealthInsurances { get; set; }
        public virtual DbSet<HomeInsurance> HomeInsurances { get; set; }
        public virtual DbSet<Insurance> Insurances { get; set; }
        public virtual DbSet<LifeInsurance> LifeInsurances { get; set; }
        public virtual DbSet<PensionPlan> PensionPlans { get; set; }
        public virtual DbSet<Purchased> Purchaseds { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TravelInsurance> TravelInsurances { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<sp_getAllVerifiedRequests_Result> sp_getAllVerifiedRequests()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAllVerifiedRequests_Result>("sp_getAllVerifiedRequests");
        }
    
        public virtual ObjectResult<sp_getHomeInsurancePendingRequests_Result> sp_getHomeInsurancePendingRequests()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getHomeInsurancePendingRequests_Result>("sp_getHomeInsurancePendingRequests");
        }
    
        public virtual ObjectResult<sp_getYourInsurances_Result> sp_getYourInsurances(Nullable<int> currentUserId)
        {
            var currentUserIdParameter = currentUserId.HasValue ?
                new ObjectParameter("CurrentUserId", currentUserId) :
                new ObjectParameter("CurrentUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getYourInsurances_Result>("sp_getYourInsurances", currentUserIdParameter);
        }
    
        public virtual ObjectResult<sp_getAutomobileInsurancePendingRequests_Result> sp_getAutomobileInsurancePendingRequests()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAutomobileInsurancePendingRequests_Result>("sp_getAutomobileInsurancePendingRequests");
        }
    
        public virtual ObjectResult<sp_getTravelInsurancePendingRequest_Result> sp_getTravelInsurancePendingRequest()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getTravelInsurancePendingRequest_Result>("sp_getTravelInsurancePendingRequest");
        }
    
        public virtual ObjectResult<sp_getHealthInsurancePendingRequest_Result> sp_getHealthInsurancePendingRequest()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getHealthInsurancePendingRequest_Result>("sp_getHealthInsurancePendingRequest");
        }
    
        public virtual ObjectResult<sp_getPensionPlanPendingRequest_Result> sp_getPensionPlanPendingRequest()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getPensionPlanPendingRequest_Result>("sp_getPensionPlanPendingRequest");
        }
    }
}
