//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject_InsuranceManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PensionPlan
    {
        public Nullable<int> CustomerId { get; set; }
        public int Age { get; set; }
        public string Occupation { get; set; }
        public long MonthlyIncome { get; set; }
        public System.DateTime PensionStartYear { get; set; }
        public Nullable<long> PensionAmount { get; set; }
        public int id { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
