//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject_InsuranceManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchased
    {
        public int PurchaseId { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<int> InsuranceId { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Insurance Insurance { get; set; }
    }
}
