//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject_InsuranceManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InsuranceManagementSystemDbEntities2 : DbContext
    {
        public InsuranceManagementSystemDbEntities2()
            : base("name=InsuranceManagementSystemDbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_getAllVerifiedRequests_Result> sp_getAllVerifiedRequests()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAllVerifiedRequests_Result>("sp_getAllVerifiedRequests");
        }
    
        public virtual ObjectResult<sp_getHomeInsurancePendingRequests_Result> sp_getHomeInsurancePendingRequests()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getHomeInsurancePendingRequests_Result>("sp_getHomeInsurancePendingRequests");
        }
    
        public virtual ObjectResult<sp_getYourInsurances_Result> sp_getYourInsurances(Nullable<int> currentUserId)
        {
            var currentUserIdParameter = currentUserId.HasValue ?
                new ObjectParameter("CurrentUserId", currentUserId) :
                new ObjectParameter("CurrentUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getYourInsurances_Result>("sp_getYourInsurances", currentUserIdParameter);
        }
    }
}
